### ISSUE TITLE
WebWallet Conformance: Metamask & Ledger Nano

### ISSUE THREAD

**Issue by okalouti** [omgnetwork/web-wallet#51]

**Comment by okalouti** [comment]
First try: 

<img width="1440" alt="Screen Shot 2563-05-25 at 15 21 02" src="https://user-images.githubusercontent.com/23177052/82816506-8ebb9900-9e9b-11ea-8984-e24361ada626.png">

**Comment by okalouti** [comment]
Exits and deposits work but you need to activate "Contract Data" on the Ledger device.

**Comment by okalouti** [comment]
<img width="1440" alt="Screen Shot 2563-05-25 at 16 41 45" src="https://user-images.githubusercontent.com/23177052/82822941-eb708100-9ea6-11ea-9d1b-0f8c7ec124cc.png">

<img width="1440" alt="Screen Shot 2563-05-25 at 16 06 29" src="https://user-images.githubusercontent.com/23177052/82822952-f1666200-9ea6-11ea-8e32-b2c203e0ae33.png">

**Comment by okalouti** [comment]
However, cannot sign child chain transactions. 

Returns `Error: Not Supported on this device.`

Understand there is no support yet for signing typed data with a hardware wallet. 
- https://github.com/MetaMask/metamask-extension/pull/5792
- https://github.com/LedgerHQ/ledgerjs/issues/86 
- https://docs.metamask.io/guide/signing-data.html#signing-data-with-metamask

**Comment by nicholasmueller** [comment]
Adding a note here since I just tried it but the watcher wont accept a signature using `personal_sign` method

**Comment by pnowosie** [comment]
> Adding a note here since I just tried it but the watcher wont accept a signature using `personal_sign` method

OMG Network transaction are signed with `eth_signTypedData` method (it's defined in [eip-712](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-712.md)). There are however some discrepacies how clients implement the method internaly (see also #omgnetwork/elixir-omg/issues/836)

**Comment by okalouti** [comment]
Picked this up on Ledger Reddit: https://www.reddit.com/r/ledgerwallet/comments/hn7c6p/ledger_support_for_eth_eip712_signtypeddata/

**Comment by unnawut** [comment]
Also inputs from @Pongch 

> TIL, went through the signature rabbit hole today, may be useful for others;  https://ethereum.stackexchange.com/questions/59880/solidity-ecrecovery-and-ethereumjs-ecsign-return-different-address
the reason signing raw private key via ecsign() works for sending transaction on the Network and not eth.sign()/personal_sign() is because web3/wallets may add the message to the prefix of the hash:
>
> ```
> "\x19Ethereum Signed Message:\n32"
> ```
> 
> before the message gets signed.
>
> only if the wallet exposes sign() without the prefix: it would be trivial to add EIP712 support like the one you see here :point_down::skin-tone-2:   and get child chain transaction to work https://github.com/ethereum/EIPs/blob/master/assets/eip-712/Example.js#L116-L128

**Comment by unnawut** [comment]
Internal Q&As for future reference:

> How low level does the integration API get? How are they able to support all the various chains they do?
> Are the questions specifically for their web3 support?

My understanding is we have these options:

1. **Integrate with metamask, then metamask talks via web3 API with the Ethereum app on ledger device:** The current hurdle is the extra prefix Ledger is appending to the signature for security reasons and metamask is not able to parse it, so we need to come up with a solution that Ledger team is willing to accept. Question 6 

2. **Integrate directly with Ethereum app on ledger device via web3 API:** Docs are little thin on signing EIP-712 this way, so hopefully we know better from those questions

3. **For different chains, especially with different signing algorithms, a party must build the ledger C app and submit it to ledger for review:** Most undesired for us due to effort required for development + submission for review. Plus UX hurdle that it diverges a lot from the usual Ethereum user flow. Would not support signing through metamask. But we might have to consider this route as a last resort.

**Comment by nicholasmueller** [comment]
And to add to the above:
- one thought was the feasibility of adjusting our system to accept personal_sign sigs (the only one ledger currently supports). Not feasible because that would affect every component in our system and the signature hashes are already well defined and verified.
- signing without prefixes (ecsign, eth_sign) is safe due to the structure of the hash and how we check it in the system

solutions:
- ledger needs to support signTypedData or ethSign (to have full ux compatibility with metamask)
- for a possible flow outside metamask, ledger needs to support some kind of api that performs the unprefixed elliptic sign 
- we write our own ledger app that performs the signing (would not fit in the metamask flow) as mentioned above
