### ISSUE TITLE
start exit sometimes fail due to out of gas

### ISSUE THREAD

**Issue by unnawut** [omgnetwork/web-wallet#81]
On sandbox

![image](https://user-images.githubusercontent.com/921194/85111610-c5889300-b23e-11ea-9462-a2fca4839e3f.png)

```
unnawut (gold team) Today at 14:49
I tried to do multiple startExit in one go on sandbox, some went through in the same block, some got cancelled, is this expected? https://rinkeby.etherscan.io/address/0x30f7632231828a5a31b45a06a84e31ea83d19490

unnawut (gold team)  17 minutes ago
Also this one got reverted even if it’s the only start exit in the block https://rinkeby.etherscan.io/tx/0x9d578b84e76e6aded592b98d9d5c2222f0714d258d87ffe29851b7e0ada80cfc

unnawut (gold team)  15 minutes ago
And doing another start exit on the same utxo a minute later got through: https://rinkeby.etherscan.io/tx/0x5bd16f7dfebbb1e9e6031727fa89c62239914529ebf342853438541aaafe838f

boolafish  15 minutes ago
seems like out of gas

boolafish  15 minutes ago
https://dashboard.tenderly.co/tx/rinkeby/0x9d578b84e76e6aded592b98d9d5c2222f0714d258d87ffe29851b7e0ada80cfc

unnawut (gold team)  14 minutes ago
ohhhh thanks, didnt spot that

jarindr the BTC road to zero  14 minutes ago
gass

boolafish  14 minutes ago
actually curious, how did you setup the gas limit?

boolafish  14 minutes ago
the estimate gas?

unnawut (gold team)  14 minutes ago
im using metamask

unnawut (gold team)  14 minutes ago
Open webwallet in 10 tabs
:mindblown:
1


boolafish  13 minutes ago
It does seems like each transaction have different gas limit that is why I am curious

unnawut (gold team)  12 minutes ago
hmmm weird, I’m just following whatever metamask suggests

boolafish  9 minutes ago
seems like metamask is calling estimate gas under the hood

jarindr the BTC road to zero  9 minutes ago
i think all libs is calling the eth client estimate gas function

kevin (gold team)  7 minutes ago
@unnawut (gold team) you should never be able to start an exit on the same utxo twice, the contract will revert the tx if you try. Is that consistent with what you're seeing?

unnawut (gold team)  7 minutes ago
@kevin (gold team) They’re all separate utxos :+1:

kevin (gold team)  7 minutes ago
cool :thumbsup:

unnawut (gold team)  5 minutes ago
Is there a better way to estimate gas? I’m guessing this is also why we see some user’s out of gas on prod? :sweat_smile:

jarindr the BTC road to zero  4 minutes ago
@unnawut (gold team) estimate gas * 2
```

Maybe there's a way to force metamask to buffer the estimated gas a bit?

**Comment by kevsul** [comment]
Hmm, not sure what we can do about this. The gas cost fluctuates a bit depending on how many exits are in the queue.
I guess that metamask estimates the gas cost, but then the queue size changes and the cost increases slightly. You _can_ increase the gas limit in MM, but a normal user won't think to do this.

**Comment by kevsul** [comment]
Actually, does metamask estimate the gas cost? Or do we do that in the wallet before sending the transaction to MM to sign?
If it's the latter, then we could always increase the gas for a start exit tx

**Comment by nicholasmueller** [comment]
yea web3 wil estimate the gas before sending to sign. 

since this is the rare case of starting 100 exits at a time, i would just bump the gas limit manually when signing in metamask. 
because in the normal case, the gas estimate seems to be working fine and the fee estimate thats shown is sane. if i add a buffer for all exits then the fee the user sees will be more expensive then what they will probably spend.

theres another issue when the gas estimation just fails. but i guess this isnt your issue.
for this case, i've implemented a fix where if gas estimation fails i will explicitly set the gas to 400000 as this is about where i see it on other exits. originally i thought i could set the gas to the upper limit of 6m but the downside of this is when the user goes to sign, the fee for the transaction looks crazy expesnive, even though this isn't what will actually be spent. @kevsul do you think a gas limit of 400k is a good default, would the gas required ever be more than that?

**Comment by kevsul** [comment]
400k gas looks reasonable, startExit with the current contracts shouldn't ever cost more than that.

**Comment by nicholasmueller** [comment]
closing for no action needed
