### ISSUE TITLE
Indefinite challenge periods ui bug

### ISSUE THREAD

**Issue by nicholasmueller** [omgnetwork/web-wallet#93]
Some old exits are still showing as being in the "challenge period" when they should be 'processable' or 'finalized'
 
Current logic of fetching/calculating challenge periods:
- Fetch `ExitStarted` events from contract
- Fetch `ExitFinalized` events from contract
- Difference in above events are in process or in challenge period events
- Get all transacted tokens to receive exit queues
- Cross reference exit ids in pending events to the exit queues

Possible reasons:
- exitableAt bug in omg-js
- exitIds are not found in the queue list because that queue is not fetched

**Comment by kevsul** [comment]
It appears that the problem is due to (at least for some cases)
 
> exitIds are not found in the queue list because that queue is not fetched

In one particular case, the user deposited some tokens and then started an exit without making any transactions. As noted above, the exit queues are only fetched for _transacted_ tokens.

Fetching exit queues for deposited _and_ transacted token fixes this
